### ISSUE TITLE
definir medidas imagenes

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#10]

**Comment by migueldiaz** [comment]
Habras visto que haydos helpers nuevos:
    <%=imagentam(@modelo,"AnchoxAlto") %>
      <%=imagen(@modelo) %>

Si quieres les añadimos una clase o una cadena del tipo mediana, pequeña, icono,... para que la generen al tamaño que quieras

**Comment by tangrammer** [comment]
esto lo hice en el uploader... funciona bien, remuestrea a 800 x 600 y genera un thumb - miniatura a 200x 200
