### ISSUE TITLE
nombre de las paginas web

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#105]
eso de que los de olearum no puedan entrar en nuestro trabajo...

si pones en internet olearum+museos o olearum+mapa, salimos noostros y los datos. puedes cambiar los nombres? pero no lo hicimos ya?

**Comment by tangrammer** [comment]
Marianna,
prefieres que no se vea nada de nada (ni interactivo) si no se escribe una
clave para acceder)??

El 24 de mayo de 2012 19:40, marionn <
reply@reply.github.com

> escribió:
> 
> eso de que los de olearum no puedan entrar en nuestro trabajo...
> 
> si pones en internet olearum+museos o olearum+mapa, salimos noostros y los
> datos. puedes cambiar los nombres? pero no lo hicimos ya?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/105

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
si, mejó. que no se enteren de ná hasta la presentación

bsssssssssssss_mrnn

El 25 de mayo de 2012 10:53, juanantonioruz <
reply@reply.github.com

> escribió:
> 
> Marianna,
> prefieres que no se vea nada de nada (ni interactivo) si no se escribe una
> clave para acceder)??
> 
> El 24 de mayo de 2012 19:40, marionn <
> reply@reply.github.com
> 
> > escribió:
> > 
> > eso de que los de olearum no puedan entrar en nuestro trabajo...
> > 
> > si pones en internet olearum+museos o olearum+mapa, salimos noostros y
> > los
> > datos. puedes cambiar los nombres? pero no lo hicimos ya?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/aceitoso/issues/105
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/105#issuecomment-5925987

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
ya está!

para acceder
usuario:aceitoso
clave:aceitoso

saludos!

El 25 de mayo de 2012 11:07, marionn <
reply@reply.github.com

> escribió:
> 
> si, mejó. que no se enteren de ná hasta la presentación
> 
> bsssssssssssss_mrnn
> 
> El 25 de mayo de 2012 10:53, juanantonioruz <
> reply@reply.github.com
> 
> > escribió:
> > 
> > Marianna,
> > prefieres que no se vea nada de nada (ni interactivo) si no se escribe
> > una
> > clave para acceder)??
> > 
> > El 24 de mayo de 2012 19:40, marionn <
> > reply@reply.github.com
> > 
> > > escribió:
> > > 
> > > eso de que los de olearum no puedan entrar en nuestro trabajo...
> > > 
> > > si pones en internet olearum+museos o olearum+mapa, salimos noostros y
> > > los
> > > datos. puedes cambiar los nombres? pero no lo hicimos ya?
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/juanantonioruz/aceitoso/issues/105
> > 
> > ## 
> > 
> > Juan Antonio Ruz
> > 
> > enJava.com = programación ágil
> > http://enJava.com
> > info@enjava.com
> > juanantonioruz@gmail.com
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/105#issuecomment-5925987
> 
> ## 
> 
> *Si sta come / d’autunno / sugli alberi / le foglie
> *Allegria di naufragi
> Giuseppe Ungaretti
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/105#issuecomment-5926200

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
