### ISSUE TITLE
clave a la página de gestión

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#112]
juan, le pones la llave de acceso también a la página http://olearum.enjava.com/admin/index??

**Comment by tangrammer** [comment]
Esta puesta, ya la tienes guardada en el navegador, por eso no la pide de
nuevo
El 30/05/2012 11:36, "marionn" <
reply@reply.github.com>
escribió:

**Comment by marionn** [comment]
haaaaaaaa_gra_bssssss

El 30 de mayo de 2012 11:38, juanantonioruz <
reply@reply.github.com

> escribió:
> 
> Esta puesta, ya la tienes guardada en el navegador, por eso no la pide de
> nuevo
> El 30/05/2012 11:36, "marionn" <
> reply@reply.github.com>
> escribió:
> 
> > juan, le pones la llave de acceso también a la página
> > http://olearum.enjava.com/admin/index??
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/aceitoso/issues/112
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/112#issuecomment-6005918

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti
