### ISSUE TITLE
al seleccionar museo que se visualiza en el mapa? bug el museo sale dos veces!

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#114]
no entiendo mu bien que es lo que se visualiza de los museos...

en museo del medio solo sale un hito de los 4 y sale 2 veces el museo

**Comment by tangrammer** [comment]
Mira que los hitos tengan las coordenadas puestas correctamente
El 06/06/2012 11:15, "marionn" <
reply@reply.github.com>
escribió:

**Comment by marionn** [comment]
hahahaha, clarooooo, ahora si! total despist

**Comment by marionn** [comment]
y donde se cargan los iconos de cada cosa? en la ficha del hito?porque salen solo los bosquecitos...

y además si hay cosas que no tienen descripción ni foto, se le puede quitar el search?

en realidad el hecho de hacer click en "search" posibilita la navegación a través de las pelotas, por lo que no es recomendable eliminar el search ok?
