### ISSUE TITLE
servicios de museo

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#115]
Buenas Miguel!

acabo de ver este bug!, se trata de los servicios del museo, se supone que en la aplicación hay unos servicios registrados.... No sé si es Service o Servicio, cada uno lleva una imagen y un titulo y esta es la url de acceso http://localhost:3000/services ó http://olearum.enjava.com/services

Y por otra parte los Museos en la Ficha tienen un listado de servicios ... 

pues el problema es que el servicio del Museo está desvinculado con el Servicio de la aplicación... es decir no tiene relación de ManyToOne.... y entonces no puedo navegar de un elemento al otro...
¿estoy equivocado o es verdad que esto hay que mejorarlo???

Saludos!

PD: antes de desplegar el código en el servidor habrá que lanzar en consola production una consulta de actualización para que no se queden las filas colgadas... esto si quieres lo hago yo una vez lo comitees vale?

**Comment by migueldiaz** [comment]
Services son los generales,
servicios son los de cada museo.
la verdad es que si es que estan desvinculados, lo que entiendo que quieres
es poder hacer service.museos,no ?
si es asi lo cambio.
Acabo de llegar de un examen de tres horas y vengo espesisimo. Mañana acabo
la segunda parte y el finde lo miro sin falta.
De todas maneras mañana si te veo hablamos,
El 6 de junio de 2012 17:56, juanantonioruz <
reply@reply.github.com

**Comment by tangrammer** [comment]
El finde perfecto! La navegacion   que hace falta seria por ejemplo:
museo.servicios(0).service.imagen
El 06/06/2012 19:20, "Miguel" <
reply@reply.github.com>
escribió:

**Comment by migueldiaz** [comment]
Ahora mismo la consulta que quieres se puede hacer
con Museo.first.servicios.first.imagen y te devuelve eso que quieres, idem
con descripción y demás campos.
Me pongo con la vinculación de todas formas.

El 6 de junio de 2012 20:25, juanantonioruz <
reply@reply.github.com

**Comment by migueldiaz** [comment]
Listo, ya esta subido, he dejado la columna imagen de servicio pero cuando se confirmen los datos se puede eliminar

**Comment by tangrammer** [comment]
Esta tarde lo miro, estoy con el chico por la mañana
Gracias!
El 08/06/2012 12:38, "Miguel" <
reply@reply.github.com>
escribió:

**Comment by migueldiaz** [comment]
ok, yo creo que hoy ando por aqui por lo que sea.
He añadido cambio de ultima hora , el modelo servicio tiene el metodo imagen.
Si se pide servicio.imagen devuelve servicio.service.imagen, si service es nulo devuelve cadena vacia, se puede reemplazar por el path a una imagen en blanco o con aviso.
