### ISSUE TITLE
Info que sale al hacer click en HITO

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#116]
Os toca decir si se pone "search" o "buscar " o cuanta info ....

**Comment by marionn** [comment]
en las ventanitas del mapa sale:

el titulo subrallado (como está ahora)
la primera frase del articulo cuando está...
(+info) > esto es el enlace al articulo que sale al lado con su eventual foto

si se pincha en la ventana del mapa, en la ventanas del articulo sale:

el titulo
la foto (NO EL ICONO y si no hay foto tampoco sale el icono)
el texto

**Comment by marionn** [comment]
esperaespera no cierres, que no nos cuadra!! lo vemos mañana?

**Comment by tangrammer** [comment]
(ir a)
morado enlace
verde oliva resto... sustituir los azulitos (147, 144, 8) valor RGB del verde!

si se hace click en hito ... en la parte izquierda de detalle que se vea el iconito chico 
siguiente linea la imagen a todo ancho
debajo el resto del texto
