### ISSUE TITLE
contenido original-colección

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#12]
en el apartado "piezas museisticas", cuando pone "Marque esta casilla para indicar que pertenece al fondo original", se entiende marcado = si; no marcado = no, pero en el listado de piezas sale la columna "coleccion"...o sea lo contrario...cambiamo la columna en "pieza original"?

**Comment by tangrammer** [comment]
ok, buena idea

El 11 de abril de 2012 13:42, marionn <
reply@reply.github.com

> escribi:
> 
> en el apartado "piezas museisticas", cuando pone "Marque esta casilla para
> indicar que pertenece al fondo original", se entiende marcado = si; no
> marcado = no, pero en el listado de piezas sale la columna "coleccion"...o
> sea lo contrario...cambiamo la columna en "pieza original"?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/12

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
miguel solo un cambio de titulo en la UI

**Comment by migueldiaz** [comment]
Cambiado por 'pieza original en la descripción' y en el formulario, coloco bien el nombre de la casilla.
 Cerrad  vosotros la issue, las dejo abiertas hasta que confirméis.

**Comment by tangrammer** [comment]
lo he pasado a radio button cierro la issue despues de comprobar en show y en edit
