### ISSUE TITLE
alarma naranja: error en Listado de Museos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#124]
han desaparecido unos museosd e la ficha http://olearum.enjava.com/museos....no me de estos sustos!!

**Comment by tangrammer** [comment]
es una cache del servidor .... One moment

El viernes, 8 de junio de 2012, marionn escribió:

> han desaparecido unos museosd e la ficha
> http://olearum.enjava.com/museos....no me de estos sustos!!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/124

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
Ya! Disculpa el retraso pero no tenía ordenador a mano....
Chao

El viernes, 8 de junio de 2012, marionn escribió:

> han desaparecido unos museosd e la ficha
> http://olearum.enjava.com/museos....no me de estos sustos!!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/124

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
