### ISSUE TITLE
pestaña como llegar en ficha museo

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#127]
la pestaña como llegar repite la info de contacto

**Comment by tangrammer** [comment]
what?

El 11 de junio de 2012 13:38, marionn <
reply@reply.github.com

> escribió:
> 
> la pestaña como llegar repite la info de contacto
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/127

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
por ejemplo:

en askjuan > museo molino del medio > como llegar...

se repite la info de la pestaña anterior contacto

2012/6/11 juanantonioruz <
reply@reply.github.com

> what?
> 
> El 11 de junio de 2012 13:38, marionn <
> reply@reply.github.com
> 
> > escribió:
> > 
> > la pestaña como llegar repite la info de contacto
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/aceitoso/issues/127
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/127#issuecomment-6242320

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti
