### ISSUE TITLE
Evento: Rehabilitación y musealización

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#132]
del molino del medio no aparece la foto que está cargada

**Comment by tangrammer** [comment]
pues es verdad...

2012/6/12 marionn <
reply@reply.github.com

> del molino del medio no aparece la foto que está cargada
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/132

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
