### ISSUE TITLE
no funciona en internet explorer

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#135]
pos eso.. he probado en un par de ordenadores y ná de ná... la visualñización de la primera página está desbaratada. en alguno dice "proccessing not found"

**Comment by tangrammer** [comment]
En teoría depende de la versión del Explorer, lo tengo que mirar pero me imagino que será alguna peculiaridad de los amigos Microsoft

**Comment by marionn** [comment]
pero se puede arreglar, no? yo pondría en las explicaciones iniciales que funciona mejor con tal navegador, crome, no?

**Comment by tangrammer** [comment]
Detalles de error de página web

Agente de usuario: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; InfoPath.2; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Fecha: Thu, 14 Jun 2012 12:51:38 UTC

Mensaje: El objeto no acepta esta acción
Línea: 793
Carácter: 37
Código: 0
URI: http://olearum.enjava.com/javascripts/processing-1.3.6.js

Mensaje: 'Processing' no está definido
Línea: 72
Carácter: 3
Código: 0
URI: http://olearum.enjava.com/

**Comment by tangrammer** [comment]
http://www.google.es/search?sourceid=chrome&ie=UTF-8&q=Processingjs+undefined#hl=es&sclient=psy-ab&q=Processingjs+undefined+ie&oq=Processingjs+undefined+ie&aq=f&aqi=&aql=&gs_l=serp.3...5024.6141.0.6363.3.3.0.0.0.0.127.335.1j2.3.0...0.0.MfzE9rVaKrU&pbx=1&bav=on.2,or.r_gc.r_pw.r_qf.,cf.osb&fp=f7be39c32f940794&biw=1054&bih=544

**Comment by tangrammer** [comment]
funciona a partir de explorer 9, tiene que ser un navegador html5 compatible!

por lo visto existe alguna solución para parchear pero no parece fácil o segura

**Comment by tangrammer** [comment]
ya he puesto la redirección provisional a una pagina donde se explica el problema falta ponerle estilo

**Comment by tangrammer** [comment]
probar askken desde win

**Comment by tangrammer** [comment]
he comprobado askken (la versión original) en explorer 8 y tampoco funciona!

**Comment by arquibernardo** [comment]
lo acabo de comprobar.... pues vaya... eso deja fuera a bastantes ordenadores... igual habría sido bueno saberlo antes....
¿se puede poner un mensaje como el del askken, incluyendo la version 9 del explorer?

**Comment by marionn** [comment]
http://www.2mdc.com/blogs/nuevas_tecnologias/asi-son-y-asi-navegan-los-internautas-espanoles

el gráfico es muy....gráfico! aunque es un poco viejo, pero por otras páginas que he visto no ha cambiado demasiado.

no es que confie en este tipo de estadisticas pero, si quitamos también la gente que usa android, cuantos podrán ver la web?

mecachi....

**Comment by tangrammer** [comment]
Vamos a ver :
- Hoy en día, el diseño web se basa en los estandares HTML5, los usuarios se adaptaran porque de lo contrario no podrán ver los contenidos. (actualizar a explorer9 no cuesta nada solo un click)
- Un interactivo del tipo que hemos hecho o se hace en flash (requiere isntalacion de plugin y en iphone e ipad no se puede... y en android es complicado), o se hace con applets (todavia más dificil requiere instalar java) o se hace con html5
- en android funciona la aplicación lo que ocurre que en la pantalla de un movil es pequeña, pero en las tabletas android funcionará y en los ipads también...
- si se entra con un navegador no compatible ya se le deriva a una pagina que se le avisa del problema.. .falta aplicar estilos
