### ISSUE TITLE
varía segun pantallas

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#136]
la visualizaión es distinta según pantallas.. ¿podemos poner algo así como "optimizado para resolución de totxtot" en la primera página?

**Comment by tangrammer** [comment]
Me gustaría ver esto con los ojos de mi cara!

**Comment by tangrammer** [comment]
he puesto un filtro que detecta si la resolución del navegador es pequeña y redirige a otra pagina avisando del problema
