### ISSUE TITLE
error al borar relaciones

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#138]
ArgumentError in GenericaRelacionsController#destroy 
wrong number of arguments (2 for 1)

Rails.root: /home/enjava/olearum
Application Trace | Framework Trace | Full Trace 
app/controllers/generica_relacions_controller.rb:8:in `destruye'
app/controllers/generica_relacions_controller.rb:8:in`destroy'
Request

Parameters: 
{"authenticity_token"=>"7xMqaH6vBwdr3o3yyPpwUObiDckTsjoocbt7uBpB+u4=",
 "_method"=>"delete",
 "id"=>"167"}

Show session dump

Show env dump
Response

Headers: 
None

**Comment by tangrammer** [comment]
Lo tengo en otras dos issues ya apuntado... Le meto mano en breve
