### ISSUE TITLE
visualizaciones de los textos y las pelotas

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#139]
cositas de textos y demás:
- REDUNDANTE CON LO SIGUIENTEPoner el título de los artículos en negrita, para que destaquen más.
- HECHO: en las pelotas, poner el texto del centro "resources" más pequeño, y sustituir "resources" por "artículos"
- HECHO: en las pelotas, poner el "artículo" más grande, y eliminar la palabra "artículo"
- IMPOSIBLE! cuando hay imagen en los artículos, dejar la imagen fija bajo el título del artículo y hacer scroll con el texto.

**Comment by tangrammer** [comment]
esto no se puede :
- cuando hay imagen en los artículos, dejar la imagen fija bajo el título del artículo y hacer scroll con el texto.

el resto si 

le meto mano en breve!
