### ISSUE TITLE
enlaces

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#14]
como pongo un enlace que me sale directamente en pdf de la página: http://www.molinodelmedio.com/ en el apartado prensa??

**Comment by tangrammer** [comment]
te pones sobre el enlace
boton derecho del raton y eliges copiar dirección del enlace
y entonces tendrás copiado el valor del enlace ...
http://www.molinodelmedio.com/pdf/molino_del_medio.pdf
y eso lo pegas en la zona de gestión>prensa

**Comment by marionn** [comment]
ok gra...
