### ISSUE TITLE
espacios en pelota y ficha de museo

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#144]
los espacios se repiten. creo que, como son calles sin salida, los quitaría de las pelotas y los dejaría solo en la ficha.

**Comment by tangrammer** [comment]
¿donde se repiten?

El 15 de junio de 2012 11:50, marionn <
reply@reply.github.com

> escribió:
> 
> los espacios se repiten. creo que, como son calles sin salida, los
> quitaría de las pelotas y los dejaría solo en la ficha.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/144

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
mira molino del medio, en la ficha, espacios

y en la pelota, espacios visitables

**Comment by tangrammer** [comment]
yo no los quitaba... porque creo que no hay que concentrar la navegacion en el desplegable....

**Comment by marionn** [comment]
vale. po entonces tienen que salir las fotos cuando se pincha en las pelotas, ahora no salen
