### ISSUE TITLE
resumen artículos como museos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#146]
puedes hacer un resumen de los artículos como has hecho para los museos? 

si no buscar lo que falta (fotos, textos...) es un follón...

**Comment by tangrammer** [comment]
?? no entiendo bien...
esto no se hace desde el listado de articulos y haciendo click en "ver"???

**Comment by marionn** [comment]
si pero hay que ver cada articulo. pero hay muchos que ya no vamos a tocar,
otros a los que le falta la imagen, otros el texto...no s epueden ver todos
desplegados, tipo resumen, para detectar lo que falta rapidamente?

2012/6/18 juanantonioruz <
reply@reply.github.com

> ?? no entiendo bien...
> esto no se hace desde el listado de articulos y haciendo click en "ver"???
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/146#issuecomment-6392573

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
quieres que en el listado de articulos aparezca un fragmento de la
descripción y su imagen?
o prefieres un boton/enlace que muestre todos los articulos que no tienen
descripción y/o imagen?

barra libre!

El 18 de junio de 2012 12:51, marionn <
reply@reply.github.com

> escribió:
> 
> si pero hay que ver cada articulo. pero hay muchos que ya no vamos a tocar,
> otros a los que le falta la imagen, otros el texto...no s epueden ver todos
> desplegados, tipo resumen, para detectar lo que falta rapidamente?
> 
> 2012/6/18 juanantonioruz <
> reply@reply.github.com
> 
> > ?? no entiendo bien...
> > esto no se hace desde el listado de articulos y haciendo click en
> > "ver"???
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/146#issuecomment-6392573
> 
> ## 
> 
> *Si sta come / d’autunno / sugli alberi / le foglie
> *Allegria di naufragi
> Giuseppe Ungaretti
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/146#issuecomment-6393039

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
preferimos la primera

ole ese programador lo bien que resuelve un lunes por la mñn!!!

El 18 de junio de 2012 13:08, juanantonioruz <
reply@reply.github.com

> escribió:
> 
> quieres que en el listado de articulos aparezca un fragmento de la
> descripción y su imagen?
> o prefieres un boton/enlace que muestre todos los articulos que no tienen
> descripción y/o imagen?
> 
> barra libre!
> 
> El 18 de junio de 2012 12:51, marionn <
> reply@reply.github.com
> 
> > escribió:
> > 
> > si pero hay que ver cada articulo. pero hay muchos que ya no vamos a
> > tocar,
> > otros a los que le falta la imagen, otros el texto...no s epueden ver
> > todos
> > desplegados, tipo resumen, para detectar lo que falta rapidamente?
> > 
> > 2012/6/18 juanantonioruz <
> > reply@reply.github.com
> > 
> > > ?? no entiendo bien...
> > > esto no se hace desde el listado de articulos y haciendo click en
> > > "ver"???
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/146#issuecomment-6392573
> > 
> > 
> > ## 
> > 
> > *Si sta come / d’autunno / sugli alberi / le foglie
> > *Allegria di naufragi
> > Giuseppe Ungaretti
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/146#issuecomment-6393039
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/146#issuecomment-6393316

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
con todala alegría que la informatica nos deja cuando no nos mira!!
ya está!
