### ISSUE TITLE
cuando se vuelve a la pelota del museo, 

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#148]
durante la navegación por pelotas, se quedan desplegadas las pestañas de la ficha y no se pueden cerrar. se puede hacer que siempre estén cerradas cuando se vuelve artás?

**Comment by tangrammer** [comment]
esto lo acabo de ver y lo acabo de arreglar!

**Comment by tangrammer** [comment]
buen ojo!
