### ISSUE TITLE
yastá el subdominio

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#149]
que dice el informático que el subdominio ya está activado. Yo he tratado de entrar por esa ruta y me dice que no lo encuentra...

www.museos.olearum.es

**Comment by tangrammer** [comment]
ya está activado!
www.museos.olearum.es

2012/6/17 arquibernardo <
reply@reply.github.com

> que dice el informático que el subdominio ya está activado. Yo he tratado
> de entrar por esa ruta y me dice que no lo encuentra...
> 
> www.museos.olearum.es
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/149

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
