### ISSUE TITLE
he hecho un fork

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#150]
pos eso...¿eso qué é?

**Comment by tangrammer** [comment]
fork=bifurcación del código
se hace para experimentar a partir de cierto estado del desarrollo
si al final de la experimentación te convence lo puedes unir a la "rama central de desarrollo" de lo contrario lo desechas

Berni a ver si te decides ya a hacerte programador que seguro que te alegras, además ahora estoy trasteando un lenguaje que ..... no veas!
