### ISSUE TITLE
foto de pieza > rodezno decazos > molino del medio

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#156]
la pone tumbada...

**Comment by tangrammer** [comment]
Mariannita si la foto está tumbada y la subes tumbada entonces se ve tumbada...
es como si camina como un pato y come como un pato podemos decir que es un pato!

**Comment by tangrammer** [comment]
la descargué la giré, la guardé y la subí... ya furula!

**Comment by marionn** [comment]
pero no estaba tumbada...o si?

2012/6/18 juanantonioruz <
reply@reply.github.com

> la descargué la giré, la guardé y la subí... ya furula!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/156#issuecomment-6392552

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
o si!

2012/6/18 marionn <
reply@reply.github.com

> pero no estaba tumbada...o si?
> 
> 2012/6/18 juanantonioruz <
> reply@reply.github.com
> 
> > la descargué la giré, la guardé y la subí... ya furula!
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/156#issuecomment-6392552
> 
> ## 
> 
> *Si sta come / d’autunno / sugli alberi / le foglie
> *Allegria di naufragi
> Giuseppe Ungaretti
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/156#issuecomment-6392993

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
