### ISSUE TITLE
parsear kml de hito si existe

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#162]

**Comment by marionn** [comment]
parsear significa que estás en ello? porque no aparecen los hotos que estoy cargando con kml. mira segorbe

**Comment by tangrammer** [comment]
todavia no he terminado con esta issue por eso que esta "OPEN"

chao!

2012/6/19 marionn <
reply@reply.github.com

> parsear significa que estás en ello? porque no aparecen los hotos que
> estoy cargando con kml. mira segorbe
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/162#issuecomment-6422863

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
kml de hito sustituir el icono que lleve por la imagen seleccionada
