### ISSUE TITLE
no se visualizan fotos de espacios de museos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#164]

**Comment by tangrammer** [comment]
que si mujer, mira museo del medio y haz click en espacios
:)

2012/6/19 marionn <
reply@reply.github.com

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/164

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
que no hombre, yo digo en los articulos, después de pinchar en el sector de
la pelota. debía haber sido más precisa. te acuerdas que estaban duplicados?

El 19 de junio de 2012 23:56, juanantonioruz <
reply@reply.github.com

> escribió:
> 
> que si mujer, mira museo del medio y haz click en espacios
> :)
> 
> 2012/6/19 marionn <
> reply@reply.github.com
> 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/aceitoso/issues/164
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/164#issuecomment-6438818

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
al hacer click en espacio detalle no sale la imagen

**Comment by tangrammer** [comment]
cuando se detalla museo ... la parte de los espacios que no salga la imagen para agilizar
