### ISSUE TITLE
Museo de la Cultura del Olivo "Hacienda la Laguna"

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#179]
no se visualiza

**Comment by tangrammer** [comment]
yo si lo veo...
¿que te ocurre exactamente?
¿no se ve el museo, las relaciones, el icono , la foto?????

2012/6/22 marionn <
reply@reply.github.com

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/179

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
no se visualizaba, después de un par de horas se ha arreglado solo...inteligencia artificial? tenemos que tenerle miedo a la criatura?

**Comment by tangrammer** [comment]
SIEMPRE!

2012/6/24 marionn <
reply@reply.github.com

> no se visualizaba, después de un par de horas se ha arreglado
> solo...inteligencia artificial? tenemos que tenerle miedo a la criatura?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/179#issuecomment-6534623

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
