### ISSUE TITLE
articulos editables con formato

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#18]

**Comment by migueldiaz** [comment]
Los artículos ya cargan el editor

He extraido el tinymce con un helper, y he rehecho un poco los menús para que queden en la misma linea sólo hay que:
- <%=cargaeditor%> en los forms
- Añadir class=>tinymce a las texareas
  Si os parece bien lo añade a todos los campos de texto

**Comment by tangrammer** [comment]
genial!
sería muy bueno que se pueda incluir a los campos descripcion

El 16 de abril de 2012 19:24, Miguel <
reply@reply.github.com

> escribió:
> 
> Los artículos ya cargan el editor
> 
> He extraido el tinymce con un helper, y he rehecho un poco los menús para
> que queden en la misma linea sólo hay que:
> - <%=cargaeditor%> en los forms
> - Añadir class=>tinymce a las texareas
>   Si os parece bien lo añade a todos los campos de texto
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/18#issuecomment-5157529

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
ok, entonces vamos confirmamos tinymce como el editor. 
Pues lo añado a las descripciones

**Comment by tangrammer** [comment]
guay!

2012/4/16 Miguel <
reply@reply.github.com

> ok, entonces vamos confirmamos tinymce como el editor.
> Pues lo añado a las descripciones
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/18#issuecomment-5157604

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
Listo, todos menos entorno.
He cambiado tu flash[:notice] por el helper alerta('info',flash[:notice])
