### ISSUE TITLE
buscador que convierte las palabras clave en enlace

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#198]
porque no funciona en todos los artículos?

**Comment by tangrammer** [comment]
??? se puede ser más explicito please?

**Comment by marionn** [comment]
por ejemplo aceite de oliva contiene iluminación y no se enlaza.
2012/6/28 juanantonioruz <
reply@reply.github.com

> ??? se puede ser más explicito please?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/198#issuecomment-6619157

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
me estoy dando cuenta ahora ... es por la tilde ... problema de caracteres... cierro esta issue y continua con la primera
#143
