### ISSUE TITLE
urgente!! milestone mañana!!

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#200]
cosas que hemos detectado con todas las cuatro covayas que han bicheado el bicho:

poner cursor con el dedo donde se pincha (inicio, sobre, logos de olearum y ministerio...)
poner cursor con mano abierta tipo pan donde se arrastra (dentro de las pelotas)
hacer que las pelotas se arrastren en todo el circulo interior blanco y no solo por el punto central
hacer que las pelotas no se salgan del perimetro de la pantalla
no visualizar los números de orden al lado de los artículos que despistan y no aportan nada

poner una lupa fija en el campo del buscador o mantener siempre escrito "buscar por palabra clave"

quitar el + del mapa cuando es pequeño
poner los botones de ampliar y reducir arriba a la derecha del mapa

hay más cosocas de diseño pero no son tan urgentes

**Comment by tangrammer** [comment]
todo hecho menos lo de limitar el perimetro de las pelotas

**Comment by marionn** [comment]
todo hecho no!! falta:

poner cursor con el dedo donde se pincha (inicio, sobre, logos de olearum y ministerio...)
poner cursor con mano abierta tipo pan donde se arrastra (dentro de las pelotas)
hacer que las pelotas se arrastren en todo el circulo interior blanco y no solo por el punto central
hacer que las pelotas no se salgan del perimetro de la pantalla (¿por hacer o no se puede?)

en el campo del buscador mantener siempre escrito "buscar por palabra clave"

quitar el + del mapa cuando es pequeño (esto no sabías si se podía hacer, pero confunde mogollón)
poner los botones de ampliar y reducir arriba a la derecha del mapa (esto tampoco sabías)

pero...que es lo que habías hecho?
