### ISSUE TITLE
listado de articulos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#21]
tenemos dificultad - mejor: preveemos dificultades - a la hora de manejar la info de los articulos. 

que tal ordenarlos por carpetas o alfabetico, reduciendo el tamaño de cada cual, como el listado de museos que solo sale el nombre y dentro tiene los apartados?

**Comment by tangrammer** [comment]
ya está corregido... lo puedes mirar en 
http://olearum.enjava.com/genericas

**Comment by tangrammer** [comment]
¿está ok así?

El 16 de abril de 2012 12:58, marionn <
reply@reply.github.com

> escribió:
> 
> tenemos dificultad - mejor: preveemos dificultades - a la hora de manejar
> la info de los articulos.
> 
> que tal ordenarlos por carpetas o alfabetico, reduciendo el tamaño de cada
> cual, como el listado de museos que solo sale el nombre y dentro tiene los
> apartados?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/21

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
muxo mejó!
