### ISSUE TITLE
no se visualizan bien los museos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#210]
en explorer9 no se visualizan los mapas y no se despliega la ficha. en opera si

**Comment by tangrammer** [comment]
me acabo de actualizar a ie9 y me funciona perfectamente

adjunto imagen

2012/6/30 marionn <
reply@reply.github.com

> en explorer9 no se visualizan los mapas y no se despliega la ficha. en
> opera si
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/210

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
ahora me funciona a mi también
