### ISSUE TITLE
¿adonde llegan los mensajes que no llegan?

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#211]
Mandé el sábado un mensaje de prueba... me dio el ok y no me ha llegado... a marianna sí ¿estará navegando por los procelosos mundos del aceite de oliva? :-)

**Comment by marionn** [comment]
a mi mayegao

El 2 de julio de 2012 09:39, arquibernardo <
reply@reply.github.com

> escribió:
> 
> Mandé el sábado un mensaje de prueba... me dio el ok y no me ha llegado...
> a marianna sí ¿estará navegando por los procelosos mundos del aceite de
> oliva? :-)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/211

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
Mira en spam
El 02/07/2012 09:39, "arquibernardo" <
reply@reply.github.com>
escribió:

**Comment by arquibernardo** [comment]
niet, niet.... a lo mejor el ordenador se ha dao cuenta de que era yo mismo 
mandándome mensajes....

----- Original Message ----- 
From: "juanantonioruz" 
reply@reply.github.com
To: "arquibernardo" arquibernardo@gmail.com
Sent: Monday, July 02, 2012 11:09 AM
Subject: Re: [aceitoso] ¿adonde llegan los mensajes que no llegan? (#211)

**Comment by tangrammer** [comment]
jolin esto furulaba...

2012/7/2 arquibernardo <
reply@reply.github.com

> niet, niet.... a lo mejor el ordenador se ha dao cuenta de que era yo mismo
> mandándome mensajes....
> 
> ----- Original Message -----
> From: "juanantonioruz"
> reply@reply.github.com
> To: "arquibernardo" arquibernardo@gmail.com
> Sent: Monday, July 02, 2012 11:09 AM
> Subject: Re: [aceitoso] ¿adonde llegan los mensajes que no llegan? (#211)
> 
> > Mira en spam
> > El 02/07/2012 09:39, "arquibernardo" <
> > reply@reply.github.com>
> > escribió:
> > 
> > > Mandé el sábado un mensaje de prueba... me dio el ok y no me ha
> > > llegado...
> > > a marianna sí ¿estará navegando por los procelosos mundos del aceite de
> > > oliva? :-)
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/juanantonioruz/aceitoso/issues/211
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/211#issuecomment-6703586
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/211#issuecomment-6705481

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by arquibernardo** [comment]
ya pita, ya.....

----- Original Message ----- 
From: "juanantonioruz" 
reply@reply.github.com
To: "arquibernardo" arquibernardo@gmail.com
Sent: Tuesday, July 03, 2012 12:42 AM
Subject: Re: [aceitoso] ¿adonde llegan los mensajes que no llegan? (#211)
