### ISSUE TITLE
adaptacion tactil a ordenadores asus de museos

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#214]
http://www.bradchen.com/blog/2011/04/processing.js-touch-events

**Comment by arquibernardo** [comment]
oye, que muy bien esto, eh?

por cierto....

....

¿qué significa?

----- Original Message ----- 
From: "juanantonioruz" 
reply@reply.github.com
To: "arquibernardo" arquibernardo@gmail.com
Sent: Tuesday, July 03, 2012 3:26 AM
Subject: [aceitoso] adaptacion tactil (#214)

**Comment by tangrammer** [comment]
Significa que parece posible
Esta noche lo ojeo

El martes, 3 de julio de 2012, arquibernardo escribió:

> oye, que muy bien esto, eh?
> 
> por cierto....
> 
> ....
> 
> ¿qué significa?
> 
> ----- Original Message -----
> From: "juanantonioruz"
> <reply@reply.github.com <javascript:;>>
> To: "arquibernardo" <arquibernardo@gmail.com <javascript:;>>
> Sent: Tuesday, July 03, 2012 3:26 AM
> Subject: [aceitoso] adaptacion tactil (#214)
> 
> > http://www.bradchen.com/blog/2011/04/processing.js-touch-events
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/aceitoso/issues/214
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/214#issuecomment-6732924

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
