### ISSUE TITLE
problema visualizacion

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#217]
ayer estaba bicheando en la web con el minipc de una amiga. es un notepad de esos que caben en un bolsillo...  pues daba el siguiente problema: al mover las pelotas por una banda horizontal que coincide con el mapa, no se podía seleccionar la pelota, ni pinchar en los concepos, n nada... si pinchabas en ese área, se marcaba en azul, como si estuviera seleccionado, toda esa banda......

**Comment by arquibernardo** [comment]
juan, no sé si habías leído esto...

**Comment by tangrammer** [comment]
Yes! El día de las instalaciones me pongo a depurar este y otros
temas(android táctil e iPad)
Chao!

El martes, 10 de julio de 2012, arquibernardo escribió:

> juan, no sé si habías leído esto...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/217#issuecomment-6873432

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
