### ISSUE TITLE
cambios en la página de inicio

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#218]
_que las pelotas se abran en el centro de la pantalla y no en la esquina de la izquierda

que el titulo "red olearum de..." sea en mayúscula y se ponga más claro cuando se navega

_que "inicio" sea más pequeño, en minúscula y más separado del campo de búsqueda

XX _poner "realizado con la ayuda..." en mayúscula: "Realizado con..."

**Comment by marionn** [comment]
falta_que las pelotas se abran en el centro de la pantalla y no en la esquina de la izquierda

**Comment by tangrammer** [comment]
Esto está en node.pjs, method setGraph()!

**Comment by tangrammer** [comment]
Done!
