### ISSUE TITLE
no me deja poner un texto...

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#23]
en museos>torno buero>espacios>molino... no me guarda el texto que pongo....

**Comment by migueldiaz** [comment]
Está funcionando, acabo de introducir el enlace a esta issue.

2012/4/16 marionn <
reply@reply.github.com

**Comment by marionn** [comment]
perdón...no había mirado el correo y pendaba que no había guardado la
issue...

gracias

El 16 de abril de 2012 18:06, Miguel <
reply@reply.github.com

> escribió:
> 
> Está funcionando, acabo de introducir el enlace a esta issue.
> 
> 2012/4/16 marionn <
> reply@reply.github.com
> 
> > en museos>torno buero>espacios>molino... no me guarda el texto que
> > pongo....
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/olearum/issues/23
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/23#issuecomment-5155795

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by migueldiaz** [comment]
La próxima la dejo abierta hasta que la confirmes. De nada

El 16 de abril de 2012 18:09, marionn <
reply@reply.github.com
