### ISSUE TITLE
issue antigua.... revisar!!... cambios en museo>entorno

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#24]
nos hemos aclarados con nosotros mismos...hay dos tipo de entradas:

1_las que estarán en las pelotas, y en el apartado entorno del museo, con sus artículos:

Variedades cultivadas
Denominación de origen
Recetas
Tradiciones y fiestas
Artesanía y arte
(y no hitos, rutas y ciudades como ahora)

2_las que sólo aparecen en el mapa, con su icono y la posibilidad de tener una ventanita con foto, texto, enlace:

Monumentos
Olivos u olivares singulares
Almazaras históricas
Colleciones
Centros urbanos
Carreteras 
Productores de aceite
casas rurales
hoteles
restaurantes
oleotecas
tiendas
viveros
centros de investigación
Instituciones relacionadas
Rutas
Alojamientos
Productores de aceite y productos relacionados
Tiendas del sector
Oleotecas
Jardín de variedades

**Comment by tangrammer** [comment]
esto me lo explicais mañana, vale?

El 16 de abril de 2012 20:29, marionn <
reply@reply.github.com

> escribió:
> 
> nos hemos aclarados con nosotros mismos...hay dos tipo de entradas:
> 
> 1_las que estarán en las pelotas, y en el apartado entorno del museo, con
> sus artículos:
> 
> Variedades cultivadas
> Denominación de origen
> Recetas
> Tradiciones y fiestas
> Artesanía y arte
> (y no hitos, rutas y ciudades como ahora)
> 
> 2_las que sólo aparecen en el mapa, con su icono y la posibilidad de tener
> una ventanita con foto, texto, enlace:
> 
> Monumentos
> Olivos u olivares singulares
> Almazaras históricas
> Colleciones
> Centros urbanos
> Carreteras
> Productores de aceite
> casas rurales
> hoteles
> restaurantes
> oleotecas
> tiendas
> viveros
> centros de investigación
> Instituciones relacionadas
> Rutas
> Alojamientos
> Productores de aceite y productos relacionados
> Tiendas del sector
> Oleotecas
> Jardín de variedades
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/24

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
Marianna ... Esta issue también se puede cerrar?
