### ISSUE TITLE
Esta página web no está disponible?????

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#250]
socorroooooo

me da error y no puedo entrar en la página....

**Comment by tangrammer** [comment]
Ya!

On Tuesday, October 9, 2012, marionn wrote:

> socorroooooo
> 
> me da error y no puedo entrar en la página....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/juanantonioruz/aceitoso/issues/250.

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
