### ISSUE TITLE
no salen los enlaces internos en el artículo "torno buera"

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#257]

**Comment by tangrammer** [comment]
¿que quiere decir "enlace interno" ?

**Comment by marionn** [comment]
los que salen en rosita y enlazan al banco de datos nuestro

2012/10/17 juanantonioruz notifications@github.com

> ¿que quiere decir "enlace interno" ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/juanantonioruz/aceitoso/issues/257#issuecomment-9523681.

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by marionn** [comment]
perdón...me acabo de dar cuenta que en los museo no hay en ninguno...optimización futura...

**Comment by tangrammer** [comment]
fixed
