### ISSUE TITLE
no se abre el wikiloc

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#263]
en los mapas, cuando se selecionan las rutas y sale el bocadillo con el enlace a la página wikiloc, no va.

**Comment by tangrammer** [comment]
fixed!

**Comment by marionn** [comment]
y esto lo has cerrado porque lo has resuelto pero todavía no se ve en red o
porque te estaba antipático?

bssssssssssssssssssss_mrnn

2013/5/6 juanantonioruz notifications@github.com

> fixed!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/juanantonioruz/aceitoso/issues/263#issuecomment-17475644
> .

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti
