### ISSUE TITLE
museos nuevos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#28]
no me deja guardar museos nuevos

**Comment by tangrammer** [comment]
lo miro ahora y te llamo

2012/4/17 marionn <
reply@reply.github.com

> no me deja guardar museos nuevos
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/28

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
ya furula

2012/4/17 JUAN ANTONIO RUZ juanantonioruz@gmail.com

> lo miro ahora y te llamo
> 
> 2012/4/17 marionn <
> reply@reply.github.com
> 
> > no me deja guardar museos nuevos
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/olearum/issues/28
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
