### ISSUE TITLE
piezas museisticas

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#30]
no se pueden guardar cambios en museos>piezas

**Comment by tangrammer** [comment]
Hola Marianna,
a mi me funciona ok ... ¿puedes describir mejor lo que estabas haciendo o
con quien lo estabas haciendo?... es decir una descripción de tu caso de
uso, ... algo más llano cómo esto:"... estaba yo editando la pieza
'Maquinaria Hidraulica' del museo de mi pueblo, y cuando le cambie el
nombre de 'maquina' por paquita me dijo que ya me gustaría a mi ver la
feria de abril ..."

2012/4/17 marionn <
reply@reply.github.com

> no se pueden guardar cambios en museos>piezas
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/30

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
jeje, dentro de poco voy a mandar a paseo de verdad a la makinaria...feria o playa...

por ejemplo: sistema de medida. le quiero poner 1 imagen pero en lugar de "guardar" sale "etiqueta" y no guarda, y no puedo editar titulo y descripción, y tampoco le veo sentido al listado que sigue...

**Comment by tangrammer** [comment]
era problema unicamente con el firefox! ya está arreglado

como yo estoy viendo la app en chrome no me había dado cuenta que el
firefox tiene problemitas visualizando ese formulario

El 17 de abril de 2012 18:12, marionn <
reply@reply.github.com

> escribió:
> 
> jeje, dentro de poco voy a mandar a paseo de verdad a la makinaria...feria
> o playa...
> 
> por ejemplo: sistema de medida. le quiero poner 1 imagen pero en lugar de
> "guardar" sale "etiqueta" y no guarda, y no puedo editar titulo y
> descripción, y tampoco le veo sentido al listado que sigue...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/30#issuecomment-5179159

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
