### ISSUE TITLE
artículos sin texto

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#31]
si un artículo no tiene todavía texto s ele puede poner automaticamente algo como "Actualmente no hay descripción para este tema"?

**Comment by tangrammer** [comment]
si!

El 17 de abril de 2012 18:15, marionn <
reply@reply.github.com

> escribió:
> 
> si un artículo no tiene todavía texto s ele puede poner automaticamente
> algo como "Actualmente no hay descripción para este tema"?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/31

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
