### ISSUE TITLE
ficha museos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#32]
holaaaaa, te reenvío esto que te asustó ayer...jeje. es la ficha técnica de los museos revisada. donde hay asteriscos hay cambios. hago un issue para cada cual?

Nombre:

Contacto:

Dirección, Teléfonos, E-correo, Página web

Titularidad, gestión y patrocinadores

Figura de protección patrimonial

Año de ingreso en olearum, cultura y patrimonio del aceite.

*\* Marca propia de aceite de oliva (con foto)

Días y horarios de apertura, precios de entrada, precios reducidos, reserva previa.

Como llegar

coordenadas geográficas/geolocalización

Espacios

Recursos interpretativos (**articulo)

**paneles

**videos

**interactivos

Piezas museísticas

Historia

Premios, reconocimientos

Publicaciones

**Historial de actividades

Servicios:

Guía
audio-guía
Material en varios idiomas
Libro de visitas
Biblioteca
Olivoteca
Punto wifi
Sala conferencias, conciertos, proyecciones
Oleo-taller
Demostración/teatralización
Catas de aceite/aceitunas
Desayuno molinero/degustación
Bar/restaurante/catering
Alojamiento
Tienda
Oleoterapia
Jardín de variedades
aseos
premios
accesibilidad minusvalidos
Contenidos especiales: Niños, Discapacitados
...

**Entorno

*_La Comarca
*_Variedades cultivadas
*_Denominación de Origen
*_Recetas
*_Tradiciones y Fiestas
*_Artesanía y Arte

iconos en el mapa

monumento
Olivos u olivares singulares
Almazaras históricas
Colecciones
Centros urbanos
Carreteras
Productores de aceite
casas rurales
hoteles
restaurantes
oleotecas
tiendas
viveros
centros de investigación
Instituciones relacionadas
Rutas
Alojamientos
Productores de aceite y productos relacionados
Tiendas del sector
Oleotecas
Jardín de variedades
punto de información
vista panorámica
área de descanso

**Comment by tangrammer** [comment]
mejor lo hablamos mañana... me paso por la nave a las 10:30?

El 17 de abril de 2012 19:26, marionn <
reply@reply.github.com

> escribió:
> 
> holaaaaa, te reenvío esto que te asustó ayer...jeje. es la ficha técnica
> de los museos revisada. donde hay asteriscos hay cambios. hago un issue
> para cada cual?
> 
> Nombre:
> 
> Contacto:
> 
> Dirección, Teléfonos, E-correo, Página web
> 
> Titularidad, gestión y patrocinadores
> 
> Figura de protección patrimonial
> 
> Año de ingreso en olearum, cultura y patrimonio del aceite.
> 
> *\* Marca propia de aceite de oliva (con foto)
> 
> Días y horarios de apertura, precios de entrada, precios reducidos,
> reserva previa.
> 
> Como llegar
> 
> coordenadas geográficas/geolocalización
> 
> Espacios
> 
> Recursos interpretativos (**articulo)
> 
> **paneles
> 
> **videos
> 
> **interactivos
> 
> Piezas museísticas
> 
> Historia
> 
> Premios, reconocimientos
> 
> Publicaciones
> 
> **Historial de actividades
> 
> Servicios:
> 
> Guía
> audio-guía
> Material en varios idiomas
> Libro de visitas
> Biblioteca
> Olivoteca
> Punto wifi
> Sala conferencias, conciertos, proyecciones
> Oleo-taller
> Demostración/teatralización
> Catas de aceite/aceitunas
> Desayuno molinero/degustación
> Bar/restaurante/catering
> Alojamiento
> Tienda
> Oleoterapia
> Jardín de variedades
> aseos
> premios
> accesibilidad minusvalidos
> Contenidos especiales: Niños, Discapacitados
> ...
> 
> **Entorno
> 
> *_La Comarca
> *_Variedades cultivadas
> *_Denominación de Origen
> *_Recetas
> *_Tradiciones y Fiestas
> *_Artesanía y Arte
> 
> iconos en el mapa
> 
> monumento
> Olivos u olivares singulares
> Almazaras históricas
> Colecciones
> Centros urbanos
> Carreteras
> Productores de aceite
> casas rurales
> hoteles
> restaurantes
> oleotecas
> tiendas
> viveros
> centros de investigación
> Instituciones relacionadas
> Rutas
> Alojamientos
> Productores de aceite y productos relacionados
> Tiendas del sector
> Oleotecas
> Jardín de variedades
> punto de información
> vista panorámica
> área de descanso
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/32

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
bale, aquí estaremos

**Comment by tangrammer** [comment]
Ficha tecnica:
- marca propia es opcional
- quitar la palabra museo del detalle de museo /show

+Espacios ... posponer
- nuevo campo de museo:recursos interpretativos resumen:texto introductorio con posibilidad de foto
- recursos interpretativos (panel, video, interactivo, maqueta): , panel, video e interactivo es una relacion con articulo ... gestion select a articulo y select tipo de recurso
- piezas museisticas... queda descripcion foto y enlace a articulo, se van las relaciones... 
  ej:navegacion museo>pieza>articulo

*\* pasamos de historial de actividades
- entorno pasa a ser como pieza más o menos
