### ISSUE TITLE
openlayers google earth degrees to meter

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#35]
http://www.google.es/search?sourceid=chrome&ie=UTF-8&q=google+marca+de+posicion+open+layes#hl=es&sclient=psy-ab&q=degrees+to+meters+openlayers&oq=degrees+to+meters+openlayers&aq=f&aqi=&aql=&gs_l=serp.3...99886l100839l3l100987l6l6l0l0l0l2l163l749l0j6l6l0.&pbx=1&bav=on.2,or.r_gc.r_pw.r_qf.,cf.osb&fp=1b3820163239e806&biw=888&bih=457

**Comment by marionn** [comment]
...y porque improvisamente hablas chino?
