### ISSUE TITLE
quillo.....

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#37]
a mí me siguen apareciendo las relaciones al revés.... mira por ejemplo la relacion entre aceite de oliva virgen extra y los monovarietales....

**Comment by tangrammer** [comment]
Puedes ser más concreto? Cuales son las monovarietales?

El miércoles 18 de abril de 2012, arquibernardo escribió:

> a mí me siguen apareciendo las relaciones al revés.... mira por ejemplo la
> relacion entre aceite de oliva virgen extra y los monovarietales....
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/37

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
