### ISSUE TITLE
quillloooooo

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#39]
tenemos un artículo que se llama aceituna... y cuando lo busco, me aparecen sólo "larecolección de la aceituna" y "utiles del trabajo de recolección de la aceituna". ¿ein? tampoco aparece "aceituna de mesa" ¿puede ser porque no tengan texto?

**Comment by tangrammer** [comment]
Si aparece, lo que pasa es que esta al final de las sugerencias del
buscador.... Si pones "acei" son tantos los resultados que se sale de las
primeras sugerencias

El miércoles 18 de abril de 2012, arquibernardo escribió:

> tenemos un artículo que se llama aceituna... y cuando lo busco, me
> aparecen sólo "larecolección de la aceituna" y "utiles del trabajo de
> recolección de la aceituna". ¿ein? tampoco aparece "aceituna de mesa"
> ¿puede ser porque no tengan texto?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/39

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by arquibernardo** [comment]
no, no... no aparecía... aparecían solamente esos dos artículos,... pero oh misterio se ha arreglado solo...
