### ISSUE TITLE
en el listado "index" que se ordenen las etiquetas segun padre/hijas

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#4]
y que se vea en el listado la relacion de etiquetas padre es decir la ruta de cada  etiqueta
ejemplo:
ruta                                     nombre
p1>p1.1>p1.1                    "nueva etiqueta"

**Comment by migueldiaz** [comment]
A ver que no lo entiendo del todo,  p1>p1.1>p1.1 "nueva etiqueta"
¿Esto es, cuando muestro una hija muestro  el padre que tenga?

**Comment by tangrammer** [comment]
el padre o los padres de forma recursiva...
as quedara ms claro a quien pertenece

y el listado que se ordene tambin as como si fuera una estructura de arbol

El 3 de abril de 2012 14:48, Miguel <
reply@reply.github.com

> escribi:
> 
> A ver que no lo entiendo del todo,  p1>p1.1>p1.1 "nueva etiqueta"
> Esto es, cuando muestro una hija muestro  el padre que tenga?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/4#issuecomment-4900238

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by migueldiaz** [comment]
En index se muestra la jerarquía de la etiqueta.
A  
A > A1
A > A1 > A11
A > A1 > A12
Creo que eso es lo que quieres, la ordenacion por este campo,... la he subido ordenando por javascript, al hacer click en cualquier columna se ordena por esa columna. Por rails al ser un campo dinámico puede ser un jaleo gordo tu lo miras y me dices si te vale así.
