### ISSUE TITLE
lo primero

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#40]
poner las relaciones en:

museo>Recursos interpretativos

museo>Piezas museísticas

museo>Entorno

luego en espacios, Historia, Premios/Reconocimientos, Publicaciones...

**Comment by tangrammer** [comment]
museo ya tiene  resumen de tipo texto introductorio de recursos interpretativos con posibilidad de foto

**Comment by tangrammer** [comment]
modelo relacionable nuevo

migracion de timestamp

class AddTimeToInfos < ActiveRecord::Migration
  def change
      def change
      add_column :infos,:updated_at, :timestamp

```
 add_column :infos,:created_at, :timestamp
```

  end

  end
end

routes
  resources :info_relacions
  resources :museo_info_relacions

```
resources :infos do
  get :relacion, :on => :member
end
```

Model

class Info < ActiveRecord::Base
  belongs_to :museo
     **acts_as_heir_of :relacionable**
  def nombre_select
    "#{self.class}: #{nombre}"  
  end

  def nombre_relacionable
    nombre
  end

end

Crear el controlador
class InfoRelacionsController < ApplicationController
  include ModuloRelaciones
   def create
     crea "relacion_museo_info"
    end

```
 def destroy
   destruye "relacion_museo_info"
 end
```

end

y las vistas index, _form... 

Actualizar las entidades existentes rails c
Info.find(:all).each{|m| Relacionable.create(:heir_id=>m.id, :heir_type=>"Info")}

**Comment by marionn** [comment]
...y todo eso lo pones para que entendamos...?

...

gracias

2012/4/19 juanantonioruz <
reply@reply.github.com

> modelo relacionable nuevo
> 
> migracion de timestamp
> 
> class AddTimeToInfos < ActiveRecord::Migration
>  def change
>      def change
>      add_column :infos,:updated_at, :timestamp
> 
> ```
> add_column :infos,:created_at, :timestamp
> ```
> 
>  end
> 
>  end
> end
> 
> routes
>  resources :info_relacions
>  resources :museo_info_relacions
> 
>    resources :infos do
>      get :relacion, :on => :member
>    end
> 
> Model
> 
> class Info < ActiveRecord::Base
>  belongs_to :museo
>    **acts_as_heir_of :relacionable**
> 
> end
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/40#issuecomment-5211523

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
Recursos interpretativos ya relacionados!

**Comment by tangrammer** [comment]
las piezas ya pueden hacer referencia o ser referenciadas por articulos

**Comment by tangrammer** [comment]
los hitos ya pueden hacer referencia o ser referenciados por articulos

las rutas ya pueden hacer referencia o ser referenciadas por articulos

**Comment by tangrammer** [comment]
los hitos y las rutas ya son relacionables
