### ISSUE TITLE
pensamientos de las 9 y 10

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#41]
me da la sensación de que lo que pasa con las pelotas de las pelotas es que no recogen las relaciones en la que el artículo en el que estamos es el destino......

**Comment by tangrammer** [comment]
Eso es lo que hablamos esta mañana... Solo pinta las relaciones de
origen... Lo corrijo esta noche

El miércoles 18 de abril de 2012, arquibernardo escribió:

> me da la sensación de que lo que pasa con las pelotas de las pelotas es
> que no recogen las relaciones en la que el artículo en el que estamos es el
> destino......
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/41

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
