### ISSUE TITLE
sugerencias de ale

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#42]
se ha pasado ale y he aprovechao...

dice algo de sustituir de forma cutre las coordenadas...y de buscar cosas sobre tom carden, que es el tío que más ha investigado en mapas y procesing

y me ha instalado el firebug (no habría tenido que dejarle, verdad?)

pa la semana próxima...

**Comment by tangrammer** [comment]
muchas gracias pero para los mapas no estamos utilizando processing sino openlayers (libreria javascript utilizada para visualización de servicios de mapas como openstreetmap o googlemap)
... otra vez será que conozcamos a este tio tom carden!
