### ISSUE TITLE
¡eureka!

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#43]
solución sencilla a eso de la pieza que duplican información de los artículos: el buscador no busca entre piezas, solo se llega a ellas a travéz del museo que la contiene

**Comment by tangrammer** [comment]
Esto es consensuado?

El miércoles 18 de abril de 2012, marionn escribió:

> solución sencilla a eso de la pieza que duplican información de los
> artículos: el buscador no busca entre piezas, solo se llega a ellas a
> travéz del museo que la contiene
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/43

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
no. es decision autoritaria mia...jeje

berni dice que si. pero si lo quitamos del buscador siguen aparecendo en las pelotas por las relaciones con los museos y los articulos, no?

**Comment by marionn** [comment]
ademàs de quitar las piezas del buscador, hay que cuidar de no repetir relaciones con el museo y con piezas y artículos con el mismo nombre

**Comment by marionn** [comment]
entre museo y articulo tiene que estar la pieza, pero que relación hay entre ellos?

museo > contiene > pieza; pieza > es ejemplo de > articulo

articulo > algunos ejemplos son > pieza; pieza > se expone en > museo

no pueden tener el mismo nombre...o hay que hecer una relación especial con localización...

museo > contiene > pieza del museo; pieza del museo > es ejemplo de > articulo

articulo > algunos ejemplos son > pieza del museo; pieza del museo > se expone en > museo

ejemplos:

articulo: prensa hidráulica
pieza: prensa hidráulica (en molino del medio)
pieza: prensa hidráulica (en museo de segorbe)
pieza: prensa hidráulica (en museo de alpicat)
...

molino del medio > contiene > prensa hidráulica del molino del medio; prensa hidráulica del molino del medio > es ejemplo de > prensa hidráulica

prensa hidráulica > algunos ejemplos son > prensa hidráulica del molino del medio; prensa hidráulica del molino del medio > se expone en > molino del medio

sencillo, no?

**Comment by arquibernardo** [comment]
yo mejor me voy tomando un cubata...

**Comment by tangrammer** [comment]
Ok!
 El 18/04/2012 23:02, "marionn" <
reply@reply.github.com>
escribió:

**Comment by marionn** [comment]
ok al cubata?
