### ISSUE TITLE
El mapa-interactivo no pinta correctamente las relaciones

### ISSUE THREAD

**Issue by arquibernardo** [juanantonioruz/aceitoso#45]
pa comprobar si pintan bien las relaciones:

Está metida la relación aceite de oliva-->se clasifica en-->aceite de oliva virgen extra

ahora mismo, En la pelota de aceite de oliva aparece   aceite de oliva-->es una clase de-->aceite de oliva virgen extra

**Comment by tangrammer** [comment]
Lo acabo de comprobar el interactivo pinta correctamente las relaciones que se indican en la zona de gestión
Relacionada la issue con #60
