### ISSUE TITLE
recorrido para la presentación

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#50]
te dejo la ruta que vamos a explicar para que verifiques que no hay problemas

home con explicaciones generales sobre visualizador-textos-mapa

navegamos: aceituna > aceite de oliva > sistemas tradicionales > prensa hidraulica > prensa hidraulica del molino del medio > molino del medio. 

aquí enseñamos el articulo-ficha, posiblemente maquetado, con imagen y también con los iconos de los servicios, y damos una vuelta entre los sectores, que tienen que ser: espacios, recursos, piezas, entorno. publicaciones y premios si puedes, a lo mejor estos pueden ser solo un listado con enlace donde procede.

luego pinchamos en una pieza y volvemos a los articulos genericos sin bichear mas, simplemente para enseñar el camino de vuelta.

luego volvemos al museo y pinchamos en entorno y hablamos del mapa y vamos a google earth

estoy un poco bloqueada con la edicion, no me deja cambiar contenido y relaciones, supongo que es por el firefox, pero ya sabes que no puedo instalar el crome

haz lo que pueda, nosotros volvemos a la carga esta noche. cuando sea operativo dame un toque y hablamos, estamos con el móvil tol dia

bssssssssssssssssssss

**Comment by tangrammer** [comment]
good morning!
me pongo con la ruta y te aviso cuando la tenga

ciaoooo

El 19 de abril de 2012 10:52, marionn <
reply@reply.github.com

> escribió:
> 
> te dejo la ruta que vamos a explicar para que verifiques que no hay
> problemas
> 
> home con explicaciones generales sobre visualizador-textos-mapa
> 
> navegamos: aceituna > aceite de oliva > sistemas tradicionales > prensa
> hidraulica > prensa hidraulica del molino del medio > molino del medio.
> 
> aquí enseñamos el articulo-ficha, posiblemente maquetado, con imagen y
> también con los iconos de los servicios, y damos una vuelta entre los
> sectores, que tienen que ser: espacios, recursos, piezas, entorno.
> publicaciones y premios si puedes, a lo mejor estos pueden ser solo un
> listado con enlace donde procede.
> 
> luego pinchamos en una pieza y volvemos a los articulos genericos sin
> bichear mas, simplemente para enseñar el camino de vuelta.
> 
> luego volvemos al museo y pinchamos en entorno y hablamos del mapa y vamos
> a google earth
> 
> estoy un poco bloqueada con la edicion, no me deja cambiar contenido y
> relaciones, supongo que es por el firefox, pero ya sabes que no puedo
> instalar el crome
> 
> haz lo que pueda, nosotros volvemos a la carga esta noche. cuando sea
> operativo dame un toque y hablamos, estamos con el móvil tol dia
> 
> bssssssssssssssssssss
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/50

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
buongiorno!!

nusotros nos vamos en un ratito y a lo mejor bicheamos al mediodía si
tenemos wifi. si no conversamos por movil y trabajamos por la noche como
los buhos

El 19 de abril de 2012 10:54, juanantonioruz <
reply@reply.github.com

> escribió:
> 
> good morning!
> me pongo con la ruta y te aviso cuando la tenga
> 
> ciaoooo
> 
> El 19 de abril de 2012 10:52, marionn <
> reply@reply.github.com
> 
> > escribió:
> > 
> > te dejo la ruta que vamos a explicar para que verifiques que no hay
> > problemas
> > 
> > home con explicaciones generales sobre visualizador-textos-mapa
> > 
> > navegamos: aceituna > aceite de oliva > sistemas tradicionales > prensa
> > hidraulica > prensa hidraulica del molino del medio > molino del medio.
> > 
> > aquí enseñamos el articulo-ficha, posiblemente maquetado, con imagen y
> > también con los iconos de los servicios, y damos una vuelta entre los
> > sectores, que tienen que ser: espacios, recursos, piezas, entorno.
> > publicaciones y premios si puedes, a lo mejor estos pueden ser solo un
> > listado con enlace donde procede.
> > 
> > luego pinchamos en una pieza y volvemos a los articulos genericos sin
> > bichear mas, simplemente para enseñar el camino de vuelta.
> > 
> > luego volvemos al museo y pinchamos en entorno y hablamos del mapa y
> > vamos
> > a google earth
> > 
> > estoy un poco bloqueada con la edicion, no me deja cambiar contenido y
> > relaciones, supongo que es por el firefox, pero ya sabes que no puedo
> > instalar el crome
> > 
> > haz lo que pueda, nosotros volvemos a la carga esta noche. cuando sea
> > operativo dame un toque y hablamos, estamos con el móvil tol dia
> > 
> > bssssssssssssssssssss
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/aceitoso/issues/50
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/50#issuecomment-5217402

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by tangrammer** [comment]
Hola marianna!
Ya casi está el recorrido ok, ... Voy a borrar las relaciones existentes en
la base de datos entre los museos y sus piezas ya que es redundante.....
Ahora las piezas pueden tener una serie de articulos relacionados
directamente desde edit de pieza,
Mejor no pongas mas info en la zona de gestión para que no haya sorpresas
mañana vale?

Me falta poner los logos todavía...

El jueves 19 de abril de 2012, marionn escribió:

> buongiorno!!
> 
> nusotros nos vamos en un ratito y a lo mejor bicheamos al mediodía si
> tenemos wifi. si no conversamos por movil y trabajamos por la noche como
> los buhos
> 
> El 19 de abril de 2012 10:54, juanantonioruz <
> reply@reply.github.com javascript:;
> 
> > escribió:
> > 
> > good morning!
> > me pongo con la ruta y te aviso cuando la tenga
> > 
> > ciaoooo
> > 
> > El 19 de abril de 2012 10:52, marionn <
> > reply@reply.github.com javascript:;
> > 
> > > escribió:
> > > 
> > > te dejo la ruta que vamos a explicar para que verifiques que no hay
> > > problemas
> > > 
> > > home con explicaciones generales sobre visualizador-textos-mapa
> > > 
> > > navegamos: aceituna > aceite de oliva > sistemas tradicionales > prensa
> > > hidraulica > prensa hidraulica del molino del medio > molino del medio.
> > > 
> > > aquí enseñamos el articulo-ficha, posiblemente maquetado, con imagen y
> > > también con los iconos de los servicios, y damos una vuelta entre los
> > > sectores, que tienen que ser: espacios, recursos, piezas, entorno.
> > > publicaciones y premios si puedes, a lo mejor estos pueden ser solo un
> > > listado con enlace donde procede.
> > > 
> > > luego pinchamos en una pieza y volvemos a los articulos genericos sin
> > > bichear mas, simplemente para enseñar el camino de vuelta.
> > > 
> > > luego volvemos al museo y pinchamos en entorno y hablamos del mapa y
> > > vamos
> > > a google earth
> > > 
> > > estoy un poco bloqueada con la edicion, no me deja cambiar contenido y
> > > relaciones, supongo que es por el firefox, pero ya sabes que no puedo
> > > instalar el crome
> > > 
> > > haz lo que pueda, nosotros volvemos a la carga esta noche. cuando sea
> > > operativo dame un toque y hablamos, estamos con el móvil tol dia
> > > 
> > > bssssssssssssssssssss
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/juanantonioruz/aceitoso/issues/50
> > 
> > ## 
> > 
> > Juan Antonio Ruz
> > 
> > enJava.com = programación ágil
> > http://enJava.com
> > info@enjava.com javascript:;
> > juanantonioruz@gmail.com javascript:;
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/50#issuecomment-5217402
> 
> ## 
> 
> *Si sta come / d’autunno / sugli alberi / le foglie
> *Allegria di naufragi
> Giuseppe Ungaretti
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/50#issuecomment-5217466

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
ya terminé!
los logos también puestos!
hablamos por telefono mañana por la mañana 
suerte!
