### ISSUE TITLE
corte en ruta

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#52]
la ruta se corta pasando de prensa hidraulica del molino del  medio a molino del medio...

**Comment by tangrammer** [comment]
arreglado!

2012/4/20 marionn <
reply@reply.github.com

> la ruta se corta pasando de prensa hidraulica del molino del  medio a
> molino del medio...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/52

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
