### ISSUE TITLE
relaciones repetidas

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#53]
en molino del medio se repiten las relaciones contiene y piezas relacionadas...

**Comment by tangrammer** [comment]
arreglado!

2012/4/20 marionn <
reply@reply.github.com

> en molino del medio se repiten las relaciones contiene y piezas
> relacionadas...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/53

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
