### ISSUE TITLE
issue antigua... debe validar mrn ... entorno no tiene articulo

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#54]

**Comment by tangrammer** [comment]
¿cómo???

2012/4/20 marionn <
reply@reply.github.com

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/54

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
idem
