### ISSUE TITLE
issue antigua... debe validar mrn ... entorno, sendero y ....

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#55]
las relaciones serían: museo > está situado en > entorno; sendero y contenido de sendero (fala, manzanilla... > está situado en > entorno

**Comment by tangrammer** [comment]
¿what??

El 20 de abril de 2012 02:16, marionn <
reply@reply.github.com

> escribió:
> 
> las relaciones serían: museo > está situado en > entorno; sendero y
> contenido de sendero (fala, manzanilla... > está situado en > entorno
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/55

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
con los cambios de las últimas reuniones se ha quedado obsoleto
