### ISSUE TITLE
al borrar la ultima relacion de un articulo peta!

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#56]
ActiveRecord::RecordNotFound in PiezasController#relacion

Couldn't find Pieza with id=68
Rails.root: /home/enjava/olearum

Application Trace | Framework Trace | Full Trace
app/controllers/piezas_controller.rb:24:in `relacion'
Request

Parameters:

{"id"=>"68",
 "museo_id"=>"1"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by migueldiaz** [comment]
Si se va a usar el respond_to do format ... hay que incluir el format.json head ok y aún así a veces da este tipo de fallos. Por eso no lo incluí en los update ni en el destroy. Es un bug de la versión de rails. A veces la petición devuelve la cabecera mal. Rails ha borrado el item pero la respuesta al navegador es mala y el js se hace un lío. Lo tienen en prioridad alta  para solucionarlo, en cuanto  tenga noticias de que lo han resuelto forzamos a usar la versión que lo resuelva.
