### ISSUE TITLE
entorno

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#57]
la categoria entorno no funciona, le he cambiado las relaciones pero no puedo cambiar el titulo y el texto, firefox me da error. porfa cambialo antes de mediodia

**Comment by tangrammer** [comment]
esta url funciona http://olearum.enjava.com/museos/1/entorno
http://olearum.enjava.com/museos/1/entorno¿qué es exactamente lo que no
furula?

El 20 de abril de 2012 02:31, marionn <
reply@reply.github.com

> escribió:
> 
> la categoria entorno no funciona, le he cambiado las relaciones pero no
> puedo cambiar el titulo y el texto, firefox me da error. porfa cambialo
> antes de mediodia
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/57

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
ahora furula

**Comment by marionn** [comment]
no, no furula

estoy en museo molino del medio > entorno > hitos > el entorno (no me explicaba bien...)

cuando le intento cambiar el nombre de "el entorno" a "Sierra de Gata" me sale este mensaje: ActiveRecord::RecordNotFound in HitosController#update 

cambialo tu porfa

**Comment by tangrammer** [comment]
ya furula la edición de rutas e hitos

El 20 de abril de 2012 02:31, marionn <
reply@reply.github.com

> escribió:
> 
> la categoria entorno no funciona, le he cambiado las relaciones pero no
> puedo cambiar el titulo y el texto, firefox me da error. porfa cambialo
> antes de mediodia
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/57

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
ya anda bien la edicion de hitos y caminos pruebalo!

El 20 de abril de 2012 03:24, marionn <
reply@reply.github.com

> escribió:
> 
> no, no furula
> 
> estoy en museo molino del medio > entorno > hitos > el entorno (no me
> explicaba bien...)
> 
> cuando le intento cambiar el nombre de "el entorno" a "Sierra de Gata" me
> sale este mensaje: ActiveRecord::RecordNotFound in HitosController#update
> 
> cambialo tu porfa
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/57#issuecomment-5236199

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
