### ISSUE TITLE
imagen con estilos de texto para descripciones de informaciones ...

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#65]
pues eso

**Comment by tangrammer** [comment]
carpeta aceitoso/pantallazo textos.tiff

**Comment by tangrammer** [comment]
sigo esperando el definitivo

**Comment by marionn** [comment]
no has hablado con bern sobre esto?

**Comment by tangrammer** [comment]
ok! entonces hoy lo "rehablo" con él

saludos

2012/6/15 marionn <
reply@reply.github.com

> no has hablado con bern sobre esto?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/65#issuecomment-6351880

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
