### ISSUE TITLE
ficha de la almazara del tio josemaria

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#69]
no me guarda la ficha!!! me da el error ese de pagina no encontrada, el cabron...

**Comment by tangrammer** [comment]
¿esto furula ya?.. .he intentado incluir despcripcion y las coordenadas del  mapa y ha funcionado... ¿y a ti?

**Comment by marionn** [comment]
he intentado poner una imagen en las piezas y me sale la página esa de error: 

La conexión ha sido reiniciada
La conexión al servidor fue reiniciada mientras la página se cargaba.

```
*   El sitio podría estar no disponible temporalmente o
     demasiado ocupado. Vuelva a intentarlo en unos momentos.

*   Si no puede cargar ninguna página, compruebe la conexión
     de red de su equipo.

*   Si su equipo o red están protegidos por un cortafuegos
     o proxy, asegúrese de que Firefox tiene permiso para
     acceder a la web.
```

**Comment by tangrammer** [comment]
esto va a ser porque la imagen es de un formato incorrecto o muy pesada...
¿me puedes enviar la imagen por el dropbox para que la vea?

saludos!

El 1 de mayo de 2012 09:36, marionn <
reply@reply.github.com

> escribió:
> 
> he intentado poner una imagen en las piezas y me sale la página esa de
> error:
> 
> La conexión ha sido reiniciada
> La conexión al servidor fue reiniciada mientras la página se cargaba.
> -   El sitio podría estar no disponible temporalmente o
>       demasiado ocupado. Vuelva a intentarlo en unos momentos.
> -   Si no puede cargar ninguna página, compruebe la conexión
>       de red de su equipo.
> -   Si su equipo o red están protegidos por un cortafuegos
>       o proxy, asegúrese de que Firefox tiene permiso para
>       acceder a la web.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/69#issuecomment-5434862

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
ya funciona, era un tiff, no los acepta? lo del otro día del error era para toda la ficha, no solo para la imagen. resuelto

**Comment by tangrammer** [comment]
Jpg gif o png son los unicos formatos admitidos en web
Saludos!
El 02/05/2012 13:50, "marionn" <
reply@reply.github.com>
escribió:
