### ISSUE TITLE
museo > visita > espacios del museo

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#75]
podrían tener relación implícita con museo a través de la palabra "visita"

q tal?

**Comment by tangrammer** [comment]
me parece muy bien y muy lógico...

**Comment by marionn** [comment]
y la relacion inversa?

pertenece a?

otra vez?

uff

**Comment by marionn** [comment]
y la relacion inversa?

pertenece a?

otra vez?

uff

**Comment by marionn** [comment]
y la relacion inversa?

pertenece a?

otra vez?

uff

**Comment by marionn** [comment]
y la relacion inversa?

pertenece a?

otra vez?

uff

**Comment by tangrammer** [comment]
En este caso " pertenece a" se entiende por contexto es decir el usuariono tiene porque saber el significado de las relaciones de las pelotas, sino que le yuda a nombrar la dirección de la relación..........
