### ISSUE TITLE
videos y audios

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#77]
¿podemos cuelgar videos y audios?

¿como?

**Comment by marionn** [comment]
entidades que lo llevan: museos

**Comment by tangrammer** [comment]
en teoría lo que vamos a hacer es colgar los audios y videos en blip.tv, youtube, vimeo o lo que sea y luego hacer un copy-paste del html embedded para incrustar el video en nuestro portal pero de esa forma nos ahorramos los problemas de alojamiento y del player de video ......

esto no es compatible con no tener internet ... en algunos museos sin internet no tendran acceso a este tipo de archivos

necesito un ejemplos publicados  de esto para probar resultado sobre interactivo

**Comment by marionn** [comment]
http://www.youtube.com/watch?v=T4NnVCF8pLE&feature=relmfu

por ejemplo....embebido en el Articulo: La recolección de la aceituna

**Comment by tangrammer** [comment]
Entonces en que entidades se van a incluir este tipo de materiales
audiovisuales...
Articulos y.... ?

2012/6/15 marionn <
reply@reply.github.com

> http://www.youtube.com/watch?v=T4NnVCF8pLE&feature=relmfu
> 
> por ejemplo....embebido en el Articulo: La recolección de la aceituna
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/77#issuecomment-6352487

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
bueno, tengo dudas...me gustaría que el material de los museos se visualizara en los museos, pero decidimos que los recursos interpretativos (eso son) no tenían nada más que el enlace al artículo. osease: en el momento en que pinchas en "video: recolección de aceitunas" en recursos interpretativos del museo de segorve, te vas al articulo general de "recolección de aceitunas", que tendrá relaciones con otros artículos y museos, pero no hay sitio en el museo para poner videos o imagenes de los recursos.

como lo hacemos?

a lo mejor en varios de la ficha del museo se pueden poner estas cosas....que tal?

**Comment by marionn** [comment]
si si si, lo tengo claro: eso va en varios de la ficha de museo

**Comment by tangrammer** [comment]
Marianna en museo , puedes añadir audiovisuales... haces click en ver museo.. .debajo de la opcion de varios... te deja incluir audiovisuales haciendo copy paste del codigo html embed que ofrecen los servicios del estilo youtube/vimeo/etc

en el interactivo de las pelotas, hay un nuevo desplegable de la ficha de museo que se llama "audiovisuales" al desplegarlo ofrece una lista de audiovisuales que al hacer click abre una nueva ventana popup con la visualización del audiovisual

CHAO!

**Comment by tangrammer** [comment]
he incluido el video del museo de segorbe!

**Comment by marionn** [comment]
no me deja abrirlo...aparece pero sin enlace

**Comment by tangrammer** [comment]
Haz click en el nombre para abrir

El lunes, 18 de junio de 2012, marionn escribió:

> no me deja abrirlo...aparece pero sin enlace
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/77#issuecomment-6395251

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
que siiiiii, que es lo que he heeeeeecho, he pinchao pero no hay enlace

El 18 de junio de 2012 16:20, juanantonioruz <
reply@reply.github.com

> escribió:
> 
> Haz click en el nombre para abrir
> 
> El lunes, 18 de junio de 2012, marionn escribió:
> 
> > no me deja abrirlo...aparece pero sin enlace
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/77#issuecomment-6395251
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/77#issuecomment-6397021

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti

**Comment by marionn** [comment]
haaaaaaaaaaaaaaaaaa

que sale y se esconde. le puedes meter la manita como a los apartado para los despistados como yo?

**Comment by tangrammer** [comment]
ya!

2012/6/18 marionn <
reply@reply.github.com

> haaaaaaaaaaaaaaaaaa
> 
> que sale y se esconde. le puedes meter la manita como a los apartado para
> los despistados como yo?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/77#issuecomment-6402023

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
