### ISSUE TITLE
borrado de etiqueta da error

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#8]
por ejemplo la p1 en modo server

**Comment by migueldiaz** [comment]
Se borran las etiquetas

**Comment by tangrammer** [comment]
la etiqueta p1 al borrar da error

2012/4/10 Miguel <
reply@reply.github.com

> Se borran las etiquetas
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/8#issuecomment-5043967

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
