### ISSUE TITLE
Desplegables

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#81]
Ficha tecnica:
- marca propia es opcional en ficha técnica

+Espacios ... posponer

**Comment by marionn** [comment]
para lo de la ficha técnica, desarollando la idea del desplegable, estos serían los parrafos/apartados:
foto
descripción (+Titularidad, gestión y patrocinadores, Figura de protección patrimonial)
contacto
como llegar
horario
servicios
varios (campos blancos – si no hay nada no aparecen):
_tienda
_venta online
_publicaciones
_aceite producción propia
_premios que otorga
_...

**Comment by tangrammer** [comment]
http://www.emenia.es/lista-desplegable-y-plegable-con-jquery/

**Comment by tangrammer** [comment]
no anda en firefox

**Comment by tangrammer** [comment]
que salga el tamaño de la imagen en la posicion inicial y dos lineas más con boton ampliar
