### ISSUE TITLE
buscar relaciones con desplegable

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#84]
como no son muchas lo prefiero a la busqueda por concordancia, que no me acuerdo de los nombre, pero si los veo si.

**Comment by tangrammer** [comment]
Ya furula esto de hacer 2 veces click en la barra espaciadora para que lance todas las sugerencias de las relaciones

**Comment by marionn** [comment]
a mi non me funciona...

**Comment by tangrammer** [comment]
Hay que hacer dos espacios.... Lo hiciste?

El jueves, 17 de mayo de 2012, marionn escribió:

> a mi non me funciona...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/84#issuecomment-5762854

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
haaaa, si funciona. 2 espacio no 2 intro

2012/5/17 juanantonioruz <
reply@reply.github.com

> Hay que hacer dos espacios.... Lo hiciste?
> 
> El jueves, 17 de mayo de 2012, marionn escribió:
> 
> > a mi non me funciona...
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/juanantonioruz/aceitoso/issues/84#issuecomment-5762854
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programación ágil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/84#issuecomment-5762923

## 

*Si sta come / d’autunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti
