### ISSUE TITLE
Definir entidades participantes en la búsqueda... Para hace un esquemita chulo y clarito

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#88]
Ahora me parece que participan:
Museo, articulo, hito, ruta....

¿Alguna más?

**Comment by tangrammer** [comment]
Marianna ¿me puedes confirmar esto?... es decir en la busqueda del interactivo de las pelotas ahora participan:
nombre de Museo, nombre de articulo, nombre de hito, nombre de ruta

... ¿alguna más???

**Comment by marionn** [comment]
si, es correcto
