### ISSUE TITLE
contenido museistico se renombra a recursos interpretativos

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#9]
solo en la ui

**Comment by marionn** [comment]
y en la frase explicativa: panele, videos...sovre contenido generl teórico.histórico

**Comment by tangrammer** [comment]
ya le has pillao el rollo!

2012/4/11 marionn <
reply@reply.github.com

> y en la frase explicativa: panele, videos...sovre contenido generl
> terico.histrico
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/9#issuecomment-5066797

## 

Juan Antonio Ruz

enJava.com = programacin gil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by marionn** [comment]
jeje, no te alegres, que voy a empezar a darte la lata...

2012/4/11 juanantonioruz <
reply@reply.github.com

> ya le has pillao el rollo!
> 
> 2012/4/11 marionn <
> reply@reply.github.com
> 
> > y en la frase explicativa: panele, videos...sovre contenido generl
> > terico.histrico
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/olearum/issues/9#issuecomment-5066797
> 
> ## 
> 
> Juan Antonio Ruz
> 
> enJava.com = programacin gil
> http://enJava.com
> info@enjava.com
> juanantonioruz@gmail.com
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/olearum/issues/9#issuecomment-5066813

## 

*Si sta come / dautunno / sugli alberi / le foglie
*Allegria di naufragi
Giuseppe Ungaretti
