### ISSUE TITLE
no me furula el askjuan

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#92]
no se carga correctamente y no responde a las búsquedas, como ayer. no vare recargar la página

**Comment by tangrammer** [comment]
Me parece que es tu navegador.... Quizás tengas que reinstalarlo...a mi me
furula bien... Sigo mirando

El viernes, 11 de mayo de 2012, marionn escribió:

> no se carga correctamente y no responde a las búsquedas, como ayer. no
> vare recargar la página
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/92

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by tangrammer** [comment]
¿se te arregló esto?

**Comment by tangrammer** [comment]
esto en teoria ya esta con el commit #c1886560449b6a3e3999068bcffe93d1c61f8815

**Comment by marionn** [comment]
furula por fin!!!!
