### ISSUE TITLE
pieza (de museo )  es relacionable??

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#93]
un ejemplo sería 
relacion de articulo "sistemas de porducción" con  "pieza prensa hidraulica del museo del molino del medio"

aunque es este momento lo hacemos ...

 "sistemas de porducción" con articulo "prensa hidraulica" con "pieza prensa hidraulica del museo del molino del medio"

**Comment by tangrammer** [comment]
se relaciona esta problematica con #87

**Comment by marionn** [comment]
creo que no, solo se llega a las piezas a través del museo y del artículo general. además para relacionar el museo con articulos generales están también los recursos, que furulan como las piezas

**Comment by marionn** [comment]
dicho con otras palabras, las piezas y los recursos interpretativos solo tienen dos sectores:

_el museo donde se exponen
_el articulo general

**Comment by tangrammer** [comment]
voy actualizando grafico

**Comment by tangrammer** [comment]
Comentando esto...
dicho con otras palabras, las piezas y los recursos interpretativos solo tienen dos sectores:

_el museo donde se exponen
_el articulo general

me da la impresión que con la pieza tiene sentido porque contiene algo más de información, pero el recurso interpretativo solo tiene el "tipo" por lo que la navegación la he puesto directamente de museo a articulo

proxima reu hablamos de esto
