### ISSUE TITLE
Pintar Elemento Geoposicionable: Museo, Hito, Ruta... ?

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#94]
¿cuales son las entidades que se visualizaran en el mapa?
Museo, Hito, Ruta

Al seleccionar un Museo... ¿qué mas se verá? Los hitos y las rutas... algo más???

¿qué mas probabilidades existen de uso? 
## DESCRIPCION TECNICA:

al hacer una busqueda del interactivo se hace una llamada ajax a rails resources_controller.search que devuelve un DatosSearch.rb en formato javascript, el cual activa el p5s a traves de network.pjs/fetchResource(resourceId) y este lo carga a través de Resource.fecthData(id) el cual hace una llamada JSON al rails (resources_controller.detalla) y obtiene un Datos.rb en formato JSON, el cual lleva la información de la pelota seleccionada: atributos y elementos

El mapa por su parte para la carga de iconos actualmente hace una llamada HTTP al rails resources_controller.textfile que le devuelve un texto con formato CVS de forma dinamica
## HAY QUE DETERMINAR

quien hace la llamada al mapa, parece que lo apropiado sería que fuera el p5s el que invoque una función  javascript que a su vez se comunique con el rails para que reciba el CVS actualizado en función del parametro id de consulta

**Comment by marionn** [comment]
en principio estos 3 

lo que se puede visualizar ademásd e los 3 (o decidir de visualizar) son cosas como los centro urbanos, las carreteras...que vienen por default en la base cartográfica.

**Comment by marionn** [comment]
me imagino que de cada elemento sale el bocadillo con "el nombre" y "+info", para cuando hay + info en forma de articulo, hito, museo o ruta. en este caso la visualización consiste en el mapa y la ventana de la derecha donde se visualizan los articulos.

**Comment by tangrammer** [comment]
Ejemplo en apache que reposiciona mapa onclickevent

http://localhost/olearum/OpenLayers-2.11/examples/resize-features.html

```
    $.mapita.setCenter(
        new OpenLayers.LonLat('"+selectedNode.getSubject().getX()+"', '"+rselectedNode.getSubject().getY()+"'), (int)random(5,10));

            $("#container_mapa").animate({
   width: "50%",
  }, 1500 );
    $("#mapa_div").animate({
   width: "100%",
  }, 1500 );
  }
```

**Comment by tangrammer** [comment]
Falta hacer los hitos dinamicos... por ahora siempre carga los hitos del museo del medio... habrá que hacer una ruta dinamica en routes.rb que recibe el id en el path ej: resources/hitostextfile/1

luego también cargar las rutas--- caminos... esto es un file KML

ya aparece el klm y escucha los eventos onclick al igual que el poi

falta hacer el klm dinamico y multiple!

**Comment by tangrammer** [comment]
## KML 

buscar kml en http://openlayers.org/dev/examples/

parseador http://openlayers.org/dev/examples/KMLParser.html

multiple layers y controls http://openlayers.org/dev/examples/select-feature-multilayer.html

## EJEMPLO que muestra descripciones....

http://openlayers.org/dev/examples/sundials.html

**Comment by marionn** [comment]
vale, me parece bien. evitamos el scroll horizontal, no?

la info se repite igual en las pelotas? podría ser resumido y si quieres saber + te vas a la visualización por pelotas, no?

He pasado esto a una issue nueva sobre visualización!

cierro la actual
