### ISSUE TITLE
rayos de pelotas demasiado largos

### ISSUE THREAD

**Issue by marionn** [juanantonioruz/aceitoso#98]
en pelota > pieza - museo … es demasiado largo, se sale de la pantalla y dificulta la lectura.

Resumir nombres de piezas y museos (lo hacemos nosotras) y poner en dos lineas?

los molinos serían:

_Hacienda Cerero
_Molino Nuevo
_La Almedina
_San Benito
_ Almazara del tío José María 
_Hacienda la Laguna
_Segorbe
_El Lagar del Mudo
_Molino del Medio
_Ca´l Agustí
_Torno Buera

**Comment by tangrammer** [comment]
Hay que incluir un nuevo campo en la bd para incluir este nuevo campo de visualizacion en el mapa

**Comment by tangrammer** [comment]
hay que quitar el sufijo del museo en la pieza
