### ISSUE TITLE
activar el registro para acceder a la gestión

### ISSUE THREAD

**Issue by tangrammer** [juanantonioruz/aceitoso#99]
Pues eso Miguel ponle ese código famoso para que cualquiera no cambie la info vale?

saludos

**Comment by migueldiaz** [comment]
ok, en local esta hecho lo subo en un rato, pongo aceitoso aceitoso, user -
pass

2012/5/18 juanantonioruz <
reply@reply.github.com

**Comment by tangrammer** [comment]
genial!

2012/5/18 Miguel <
reply@reply.github.com

> ok, en local esta hecho lo subo en un rato, pongo aceitoso aceitoso, user -
> pass
> 
> 2012/5/18 juanantonioruz <
> reply@reply.github.com
> 
> > Pues eso Miguel ponle ese código famoso para que cualquiera no cambie la
> > info vale?
> > 
> > saludos
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/juanantonioruz/aceitoso/issues/99
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/99#issuecomment-5785310

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com

**Comment by arquibernardo** [comment]
Si te parece el lunes lo hablamos.. podrias hacer la factura con fecha uno 
de junio, no te va a afectar a declaraciones y retenciones porque entra en 
el mismo trimestre que si la hicieras en Mayo... y tu puedes declararla como 
si la hubieras hecho en ese mes....

**Comment by tangrammer** [comment]
OK!

El 25 de mayo de 2012 11:51, arquibernardo <
reply@reply.github.com

> escribió:
> 
> Si te parece el lunes lo hablamos.. podrias hacer la factura con fecha uno
> de junio, no te va a afectar a declaraciones y retenciones porque entra en
> el mismo trimestre que si la hicieras en Mayo... y tu puedes declararla
> como
> si la hubieras hecho en ese mes....
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/juanantonioruz/aceitoso/issues/99#issuecomment-5926853

## 

Juan Antonio Ruz

enJava.com = programación ágil
http://enJava.com
info@enjava.com
juanantonioruz@gmail.com
